using System.Text;
using System.Text.Json;

namespace DotNetPerformanceLab;

public static class PlotlyReportExporter
{
    private const string PlotlyPackage = "plotly.js-basic-dist-min";

    public static async Task WriteAsync(
        string outputDirectory,
        PerformanceRunResult result,
        IReadOnlyList<MetricSample> metrics,
        CancellationToken cancellationToken,
        string? assetSourceDirectory = null)
    {
        var sourceDirectory = ResolveAssetSource(assetSourceDirectory);
        var siteDirectory = Path.Combine(outputDirectory, "web-report");
        var assetDirectory = Path.Combine(siteDirectory, "assets");
        var licenseDirectory = Path.Combine(assetDirectory, "licenses");
        Directory.CreateDirectory(licenseDirectory);

        File.Copy(Path.Combine(sourceDirectory, "dashboard.js"), Path.Combine(assetDirectory, "dashboard.js"));
        File.Copy(Path.Combine(sourceDirectory, "dashboard.css"), Path.Combine(assetDirectory, "dashboard.css"));
        File.Copy(
            Path.Combine(sourceDirectory, "node_modules", PlotlyPackage, "plotly-basic.min.js"),
            Path.Combine(assetDirectory, "plotly-basic.min.js"));
        File.Copy(
            Path.Combine(sourceDirectory, "node_modules", PlotlyPackage, "LICENSE"),
            Path.Combine(licenseDirectory, "plotly-js.txt"));

        var payload = new WebReportPayload(result.ReportLabel, result.GeneratedUtc, result.Environment, metrics);
        var json = JsonSerializer.Serialize(payload, LabJsonContext.Default.WebReportPayload);
        await File.WriteAllTextAsync(
            Path.Combine(assetDirectory, "data.js"),
            $"globalThis.DPL_REPORT = {json};{Environment.NewLine}",
            new UTF8Encoding(false),
            cancellationToken).ConfigureAwait(false);
        await File.WriteAllTextAsync(
            Path.Combine(siteDirectory, "index.html"),
            Html,
            new UTF8Encoding(false),
            cancellationToken).ConfigureAwait(false);
    }

    private static string ResolveAssetSource(string? assetSourceDirectory)
    {
        var configured = Environment.GetEnvironmentVariable("DPL_WEB_ASSETS_DIRECTORY");
        var directory = !string.IsNullOrWhiteSpace(assetSourceDirectory)
            ? Path.GetFullPath(assetSourceDirectory)
            : string.IsNullOrWhiteSpace(configured)
                ? Path.Combine(Environment.CurrentDirectory, "web")
                : Path.GetFullPath(configured);
        var required = new[]
        {
            Path.Combine(directory, "dashboard.js"),
            Path.Combine(directory, "dashboard.css"),
            Path.Combine(directory, "node_modules", PlotlyPackage, "plotly-basic.min.js"),
            Path.Combine(directory, "node_modules", PlotlyPackage, "LICENSE")
        };
        var missing = required.FirstOrDefault(path => !File.Exists(path));
        return missing is null
            ? directory
            : throw new InvalidOperationException(
                $"Plotly report assets are missing: {missing}. Run 'npm ci --prefix web --ignore-scripts' before analysis.");
    }

    private const string Html = """
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <meta name="color-scheme" content="dark">
          <title>.NET Performance Analysis</title>
          <link rel="stylesheet" href="assets/dashboard.css">
        </head>
        <body>
          <header>
            <h1 id="target">.NET Performance Analysis</h1>
            <div class="subtitle">Interactive process, host, and runtime metrics</div>
          </header>
          <main>
            <section class="summary" aria-label="Report summary">
              <article class="card"><div class="label">Generated</div><div class="value" id="generated">—</div></article>
              <article class="card"><div class="label">Environment</div><div class="value" id="environment">—</div></article>
              <article class="card"><div class="label">Selection</div><div class="value" id="status">—</div></article>
            </section>
            <section class="toolbar" aria-label="Chart controls">
              <label>Scope<select id="scope"></select></label>
              <label>Metric<select id="metric"></select></label>
            </section>
            <section class="panel"><div id="chart" role="img" aria-label="Selected performance metric chart"></div></section>
            <footer>Generated by DotNetPerformanceLab. Plotly.js is distributed under the MIT License.</footer>
          </main>
          <script src="assets/plotly-basic.min.js"></script>
          <script src="assets/data.js"></script>
          <script src="assets/dashboard.js"></script>
        </body>
        </html>
        """;
}

public sealed record WebReportPayload(
    string Target,
    DateTimeOffset GeneratedUtc,
    EnvironmentSnapshot Environment,
    IReadOnlyList<MetricSample> Metrics);
